# Generated by Django 6.0.2 on 2026-02-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'period_number']},
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(help_text='Format: HH:MM (Example: 10:20)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(help_text='Format: HH:MM (Example: 09:30)'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'day', 'period_number')},
        ),
    ]
