# Generated by Django 6.0.2 on 2026-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_timetable_options_timetable_period_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(help_text='End time of the period (HH:MM)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_number',
            field=models.IntegerField(default=1, help_text='Enter the period number (e.g., 1 for first period, 2 for second, etc.)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(help_text='Start time of the period (HH:MM)'),
        ),
    ]
