# Generated by Django 6.0.2 on 2026-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_id_alter_classroom_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-timestamp']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
