# Generated by Django 6.0.2 on 2026-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_options_attendance_absent_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
