# Generated by Django 6.0.2 on 2026-02-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'start_time']},
        ),
    ]
